# Creating a logistic regression to predict absenteeism

## Import the relevant libraries

In [1]:
# import the relevant libraries
import pandas as pd
import numpy as np

## Load the data

In [3]:
# load the preprocessed CSV data
data_preprocessed = pd.read_csv('Absenteeism-preprocessed.csv')

In [4]:
# eyeball the data
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

## Create the targets

In [5]:
# find the median of 'Absenteeism Time in Hours'
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
# create targets for our logistic regression
# they have to be categories and we must find a way to say if someone is 'being absent too much' or not
# what we've decided to do is to take the median of the dataset as a cut-off line
# in this way the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression)
# as balancing is a great problem for ML, this will work great for us
# alternatively, if we had more data, we could have found other ways to deal with the issue 
# for instance, we could have assigned some arbitrary value as a cut-off line, instead of the median

# note that what line does is to assign 1 to anyone who has been absent 4 hours or more (more than 3 hours)
# that is the equivalent of taking half a day off

# initial code from the lecture
# targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

# parameterized code
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [7]:
# eyeball the targets
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [8]:
# create a Series in the original data frame that will contain the targets for the regression
data_preprocessed['Excessive Absenteeism'] = targets

In [9]:
# check what happened
# maybe manually see how the targets were created
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

## A comment on the targets

In [10]:
# check if dataset is balanced (what % of targets are 1s)
# targets.sum() will give us the number of 1s that there are
# the shape[0] will give us the length of the targets array
targets.sum() / targets.shape[0]

0.45571428571428574

In [11]:
# create a checkpoint by dropping the unnecessary variables
# also drop the variables we 'eliminated' after exploring the weights
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [12]:
# check if the line above is a checkpoint :)

# if data_with_targets is data_preprocessed = True, then the two are pointing to the same object
# if it is False, then the two variables are completely different and this is in fact a checkpoint
data_with_targets is data_preprocessed

False

In [13]:
# check what's inside
data_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,0

## Select the inputs for the regression

In [14]:
data_with_targets.shape

(700, 15)

In [15]:
# Selects all rows and all columns until 14 (excluding)
data_with_targets.iloc[:,:14]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1
5,0,0,0,1,10,2,179,51,38,239.554,31,0,0,0
6,0,0,0,1,7,4,361,52,28,239.554,27,0,1,4
7,0,0,0,1,7,4,260,50,36,239.554,23,0,4,0
8,0,0,1,0,6,6,155,12,34,239.554,25,0,2,0
9,0,0,0,1,7,0,235,11,37,239.554,29,1,1,1
10,1,0,0,0,7,0,260,50,36,239.554,23,0,4,0
11,1,0,0,0,7,1,260,50,36,239.554,23,0,4,0
12,1,0,0,0,7,2,260,50,36,239.554,23,0,4,0
13,1,0,0,0,7,2,179,51,38,239.554,31,0,0,0
14,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0
15,1,0,0,0,7,4,246,25,41,239.554,23,0,0,0
16,0,0,0,1,7,4,179,51,38,239.554,31,0,0,0
17,0,0,1,0,7,0,179,51,38,239.554,31,0,0,0
18,1,0,0,0,7,3,189,29,33,239.554,25,0,2,2
19,0,0,0,1,5,4,248,25,47,205.917,32,0,2,1
20,1,0,0,0,12,1,330,16,28,205.917,25,1,0,0
21,1,0,0,0,3,6,179,51,38,205.917,31,0,0,0
22,1,0,0,0,10,3,361,52,28,205.917,27,0,1,4
23,0,0,0,1,8,4,260,50,36,205.917,23,0,4,0
24,0,0,1,0,8,0,289,36,33,205.917,30,0,2,1
25,0,0,0,1,8,0,361,52,28,205.917,27,0,1,4
26,0,0,0,1,4,2,289,36,33,205.917,30,0,2,1
27,0,0,0,1,12,1,157,27,29,205.917,22,0,0,0
28,0,0,1,0,8,2,289,36,33,205.917,30,0,2,1
29,0,0,0,1,8,4,179,51,38,205.917,31,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,1,155,12,34,246.288,25,0,2,0
671,0,0,1,0,4,3,225,26,28,246.288,24,0,1,2
672,1,0,0,0,4,3,118,13,50,246.288,31,0,1,0
673,0,0,0,1,4,4,179,26,30,246.288,19,1,0,0
674,0,0,0,1,7,3,235,11,37,237.656,29,1,1,1
675,0,0,1,0,9,2,225,15,41,237.656,28,1,2,2
676,0,0,0,1,9,2,235,16,32,237.656,25,1,0,0
677,1,0,0,0,9,2,118,10,37,237.656,28,0,0,0
678,0,0,0,1,9,2,235,20,43,237.656,38,0,1,0
679,1,0,0,0,10,4,179,26,30,237.656,19,1,0,0
680,0,0,0,1,10,4,291,31,40,237.656,25,0,1,1
681,1,0,0,0,10,4,225,15,41,237.656,28,1,2,2
682,0,0,1,0,11,0,300,26,43,237.656,25,0,2,1
683,0,0,0,1,11,0,225,15,41,237.656,28,1,2,2
684,0,0,0,1,11,0,179,26,30,237.656,19,1,0,0
685,0,0,0,1,5,0,118,13,50,237.656,31,0,1,0
686,1,0,0,0,5,1,118,13,50,237.656,31,0,1,0
687,0,0,0,1,5,1,118,10,37,237.656,28,0,0,0
688,0,0,0,0,5,1,118,13,50,237.656,31,0,1,0
689,0,0,0,1,5,2,179,26,30,237.656,19,1,0,0
690,0,0,0,0,5,2,378,49,36,237.656,21,0,2,4
691,0,1,0,0,5,4,179,22,40,237.656,22,1,2,0
692,1,0,0,0,5,0,155,12,34,237.656,25,0,2,0
693,1,0,0,0,5,0,235,16,32,237.656,25,1,0,0
694,0,0,0,1,5,2,291,31,40,237.656,25,0,1,1
695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0
696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2
697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0
698,0,0,0,1,5,3,235,16,32,237.656,25,1,0,0
699,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1

In [16]:
# Selects all rows and all columns but the last one (basically the same operation)
data_with_targets.iloc[:,:-1]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1
5,0,0,0,1,10,2,179,51,38,239.554,31,0,0,0
6,0,0,0,1,7,4,361,52,28,239.554,27,0,1,4
7,0,0,0,1,7,4,260,50,36,239.554,23,0,4,0
8,0,0,1,0,6,6,155,12,34,239.554,25,0,2,0
9,0,0,0,1,7,0,235,11,37,239.554,29,1,1,1
10,1,0,0,0,7,0,260,50,36,239.554,23,0,4,0
11,1,0,0,0,7,1,260,50,36,239.554,23,0,4,0
12,1,0,0,0,7,2,260,50,36,239.554,23,0,4,0
13,1,0,0,0,7,2,179,51,38,239.554,31,0,0,0
14,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0
15,1,0,0,0,7,4,246,25,41,239.554,23,0,0,0
16,0,0,0,1,7,4,179,51,38,239.554,31,0,0,0
17,0,0,1,0,7,0,179,51,38,239.554,31,0,0,0
18,1,0,0,0,7,3,189,29,33,239.554,25,0,2,2
19,0,0,0,1,5,4,248,25,47,205.917,32,0,2,1
20,1,0,0,0,12,1,330,16,28,205.917,25,1,0,0
21,1,0,0,0,3,6,179,51,38,205.917,31,0,0,0
22,1,0,0,0,10,3,361,52,28,205.917,27,0,1,4
23,0,0,0,1,8,4,260,50,36,205.917,23,0,4,0
24,0,0,1,0,8,0,289,36,33,205.917,30,0,2,1
25,0,0,0,1,8,0,361,52,28,205.917,27,0,1,4
26,0,0,0,1,4,2,289,36,33,205.917,30,0,2,1
27,0,0,0,1,12,1,157,27,29,205.917,22,0,0,0
28,0,0,1,0,8,2,289,36,33,205.917,30,0,2,1
29,0,0,0,1,8,4,179,51,38,205.917,31,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,1,155,12,34,246.288,25,0,2,0
671,0,0,1,0,4,3,225,26,28,246.288,24,0,1,2
672,1,0,0,0,4,3,118,13,50,246.288,31,0,1,0
673,0,0,0,1,4,4,179,26,30,246.288,19,1,0,0
674,0,0,0,1,7,3,235,11,37,237.656,29,1,1,1
675,0,0,1,0,9,2,225,15,41,237.656,28,1,2,2
676,0,0,0,1,9,2,235,16,32,237.656,25,1,0,0
677,1,0,0,0,9,2,118,10,37,237.656,28,0,0,0
678,0,0,0,1,9,2,235,20,43,237.656,38,0,1,0
679,1,0,0,0,10,4,179,26,30,237.656,19,1,0,0
680,0,0,0,1,10,4,291,31,40,237.656,25,0,1,1
681,1,0,0,0,10,4,225,15,41,237.656,28,1,2,2
682,0,0,1,0,11,0,300,26,43,237.656,25,0,2,1
683,0,0,0,1,11,0,225,15,41,237.656,28,1,2,2
684,0,0,0,1,11,0,179,26,30,237.656,19,1,0,0
685,0,0,0,1,5,0,118,13,50,237.656,31,0,1,0
686,1,0,0,0,5,1,118,13,50,237.656,31,0,1,0
687,0,0,0,1,5,1,118,10,37,237.656,28,0,0,0
688,0,0,0,0,5,1,118,13,50,237.656,31,0,1,0
689,0,0,0,1,5,2,179,26,30,237.656,19,1,0,0
690,0,0,0,0,5,2,378,49,36,237.656,21,0,2,4
691,0,1,0,0,5,4,179,22,40,237.656,22,1,2,0
692,1,0,0,0,5,0,155,12,34,237.656,25,0,2,0
693,1,0,0,0,5,0,235,16,32,237.656,25,1,0,0
694,0,0,0,1,5,2,291,31,40,237.656,25,0,1,1
695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0
696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2
697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0
698,0,0,0,1,5,3,235,16,32,237.656,25,1,0,0
699,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1

In [17]:
# Create a variable that will contain the inputs (everything without the targets)
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

standardize the inputs

standardization is one of the most common preprocessing tools
 since data of different magnitude (scale) can be biased towards high values,
we want all inputs to be of similar magnitude
this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

a very useful module we can use is StandardScaler 
it has much more capabilities than the straightforward 'preprocessing' method

import the libraries needed to create the Custom Scaler
note that all of them are a part of the sklearn package
 moreover, one of them is actually the StandardScaler module, 
so you can imagine that the Custom Scaler is build on it

We will  create the Custom Scaler class

    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do

In [67]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

In [78]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet'],
       copy=None, with_mean=None, with_std=None)

In [79]:
# this operation will transform the unscaled input using the information contained
# in the absenteeism scale. in simple words, we are subtracting the mean and dividing by standard deviation
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [80]:
scaled_inputs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet
0,0,0,0,1,0.030796,-0.800950,1.005844,0.412816,-0.536062,-0.806331,0.767431,0,0.880469,0.268487
1,0,0,0,0,0.030796,-0.800950,-1.574681,-1.141882,2.130803,-0.806331,1.002633,0,-0.019280,-0.589690
2,0,0,0,1,0.030796,-0.232900,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690
3,1,0,0,0,0.030796,0.335149,0.854936,-1.682647,0.405184,-0.806331,-0.643782,0,0.880469,-0.589690
4,0,0,0,1,0.030796,0.335149,1.005844,0.412816,-0.536062,-0.806331,0.767431,0,0.880469,0.268487
5,0,0,0,1,0.929019,-0.232900,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690
6,0,0,0,1,0.030796,0.903199,2.092381,1.494345,-1.320435,-0.806331,0.061825,0,-0.019280,2.843016
7,0,0,0,1,0.030796,0.903199,0.568211,1.359154,-0.065439,-0.806331,-0.878984,0,2.679969,-0.589690
8,0,0,1,0,-0.268611,2.039298,-1.016322,-1.209478,-0.379188,-0.806331,-0.408580,0,0.880469,-0.589690
9,0,0,0,1,0.030796,-1.368999,0.190942,-1.277074,0.091435,-0.806331,0.532229,1,-0.019280,0.268487
10,1,0,0,0,0.030796,-1.368999,0.568211,1.359154,-0.065439,-0.806331,-0.878984,0,2.679969,-0.589690
11,1,0,0,0,0.030796,-0.800950,0.568211,1.359154,-0.065439,-0.806331,-0.878984,0,2.679969,-0.589690
12,1,0,0,0,0.030796,-0.232900,0.568211,1.359154,-0.065439,-0.806331,-0.878984,0,2.679969,-0.589690
13,1,0,0,0,0.030796,-0.232900,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690
14,0,0,0,1,0.030796,-0.232900,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690
15,1,0,0,0,0.030796,0.903199,0.356940,-0.330735,0.718933,-0.806331,-0.878984,0,-0.919030,-0.589690
16,0,0,0,1,0.030796,0.903199,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690
17,0,0,1,0,0.030796,-1.368999,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690
18,1,0,0,0,0.030796,0.335149,-0.503235,-0.060353,-0.536062,-0.806331,-0.408580,0,0.880469,1.126663
19,0,0,0,1,-0.568019,0.903199,0.387122,-0.330735,1.660180,-1.647399,1.237836,0,0.880469,0.268487
20,1,0,0,0,1.527833,-0.800950,1.624567,-0.939096,-1.320435,-1.647399,-0.408580,1,-0.919030,-0.589690
21,1,0,0,0,-1.166834,2.039298,-0.654143,1.426749,0.248310,-1.647399,1.002633,0,-0.919030,-0.589690
22,1,0,0,0,0.929019,0.335149,2.092381,1.494345,-1.320435,-1.647399,0.061825,0,-0.019280,2.843016
23,0,0,0,1,0.330204,0.903199,0.568211,1.359154,-0.065439,-1.647399,-0.878984,0,2.679969,-0.589690
24,0,0,1,0,0.330204,-1.368999,1.005844,0.412816,-0.536062,-1.647399,0.767431,0,0.880469,0.268487
25,0,0,0,1,0.330204,-1.368999,2.092381,1.494345,-1.320435,-1.647399,0.061825,0,-0.019280,2.843016
26,0,0,0,1,-0.867426,-0.232900,1.005844,0.412816,-0.536062,-1.647399,0.767431,0,0.880469,0.268487
27,0,0,0,1,1.527833,-0.800950,-0.986140,-0.195544,-1.163560,-1.647399,-1.114186,0,-0.919030,-0.589690
28,0,0,1,0,0.330204,-0.232900,1.005844,0.412816,-0.536062,-1.647399,0.767431,0,0.880469,0.268487
29,0,0,0,1,0.330204,0.903199,-0.654143,1.426749,0.248310,-1.647399,1.002633,0,-0.919030,-0.589690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,-0.867426,-0.800950,-1.016322,-1.209478,-0.379188,-0.637953,-0.408580,0,0.880469,-0.589690
671,0,0,1,0,-0.867426,0.335149,0.040034,-0.263140,-1.320435,-0.637953,-0.643782,0,-0.019280,1.126663
672,1,0,0,0,-0.867426,0.335149,-1.574681,-1.141882,2.130803,-0.637953,1.002633,0,-0.019280,-0.589690
673,0,0,0,1,-0.867426,0.903199,-0.654143,-0.263140,-1.006686,-0.637953,-1.819793,1,-0.919030,-0.589690
674,0,0,0,1,0.030796,0.335149,0.190942,-1.277074,0.091435,-0.853789,0.532229,1,-0.019280,0.268487
675,0,0,1,0,0.629611,-0.232900,0.040034,-1.006691,0.718933,-0.853789,0.297027,1,0.880469,1.126663
676,0,0,0,1,0.629611,-0.232900,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,1,-0.919030,-0.589690
677,1,0,0,0,0.629611,-0.232900,-1.574681,-1.344669,0.091435,-0.853789,0.297027,0,-0.919030,-0.589690
678,0,0,0,1,0.629611,-0.232900,0.190942,-0.668713,1.032682,-0.853789,2.649049,0,-0.019280,-0.589690
679,1,0,0,0,0.929019,0.903199,-0.654143,-0.263140,-1.006686,-0.853789,-1.819793,1,-0.919030,-0.589690
680,0,0,0,1,0.929019,0.903199,1.036026,0.074838,0.562059,-0.853789,-0.408580,0,-0.019280,0.268487
681,1,0,0,0,0.929019,0.903199,0.040034,-1.006691,0.718933,-0.853789,0.297027,1,0.880469,1.126663
682,0,0,1,0,1.228426,-1.368999,1.171843,-0.263140,1.032682,-0.853789,-0.408580,0,0.880469,0.268487
683,0,0,0,1,1.228426,-1.368999,0.040034,-1.006691,0.718933,-0.853789,0.297027,1,0.880469,1.126663
684,0,0,0,1,1.228426,-1.368999,-0.654143,-0.263140,-1.006686,-0.853789,-1.819793,1,-0.919030,-0.589690
685,0,0,0,1,-0.568019,-1.368999,-1.574681,-1.141882,2.130803,-0.853789,1.002633,0,-0.019280,-0.589690
686,1,0,0,0,-0.568019,-0.800950,-1.574681,-1.141882,2.130803,-0.853789,1.002633,0,-0.019280,-0.589690
687,0,0,0,1,-0.568019,-0.800950,-1.574681,-1.344669,0.091435,-0.853789,0.297027,0,-0.919030,-0.589690
688,0,0,0,0,-0.568019,-0.800950,-1.574681,-1.141882,2.130803,-0.853789,1.002633,0,-0.019280,-0.589690
689,0,0,0,1,-0.568019,-0.232900,-0.654143,-0.263140,-1.006686,-0.853789,-1.819793,1,-0.919030,-0.589690
690,0,0,0,0,-0.568019,-0.232900,2.348925,1.291558,-0.065439,-0.853789,-1.349389,0,0.880469,2.843016
691,0,1,0,0,-0.568019,0.903199,-0.654143,-0.533522,0.562059,-0.853789,-1.114186,1,0.880469,-0.589690
692,1,0,0,0,-0.568019,-1.368999,-1.016322,-1.209478,-0.379188,-0.853789,-0.408580,0,0.880469,-0.589690
693,1,0,0,0,-0.568019,-1.368999,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,1,-0.919030,-0.589690
694,0,0,0,1,-0.568019,-0.232900,1.036026,0.074838,0.562059,-0.853789,-0.408580,0,-0.019280,0.268487
695,1,0,0,0,-0.568019,-0.232900,-0.654143,-0.533522,0.562059,-0.853789,-1.114186,1,0.880469,-0.589690
696,1,0,0,0,-0.568019,-0.232900,0.040034,-0.263140,-1.320435,-0.853789,-0.643782,0,-0.019280,1.126663
697,1,0,0,0,-0.568019,0.335149,1.624567,-0.939096,-1.320435,-0.853789,-0.408580,1,-0.919030,-0.589690
698,0,0,0,1,-0.568019,0.335149,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,1,-0.919030,-0.589690
699,0,0,0,1,-0.568019,0.335149,1.036026,0.074838,0.562059,-0.853789,-0.408580,0,-0.019280,0.268487

Finally, all the input data has been standardized.

In [81]:
# check the shape of the inputs
scaled_inputs.shape

(700, 14)

this shows us that we have got 700 observertions and 14 features

## Split the data into train & test and shuffle

### Import the relevant module

In [82]:
# import train_test_split so we can split our data into train and test
from sklearn.model_selection import train_test_split

### Split

In [83]:
# check how this method works
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 421         0         0         0         1    -0.867426         0.903199
 414         0         0         0         1     0.030796        -0.800950
 548         0         0         0         0     1.228426        -0.800950
 649         0         0         0         1    -1.166834        -0.232900
 98          0         0         0         1    -1.765648        -1.368999
 639         0         0         0         1    -1.166834        -0.232900
 612         0         0         0         1    -1.466241        -0.800950
 412         0         0         0         1    -0.568019         0.335149
 164         1         0         0         0     0.030796         2.039298
 663         0         0         0         1     0.929019         0.335149
 497         0         0         0         1    -0.568019        -0.800950
 360         0         0         0         1     0.629611         0.903199
 153         0         0         0         1    -1.466241        -0.232900
 217         1         0         0         0    -0.568019        -0.800950
 464         0         0         0         1     0.030796         0.903199
 309         0         0         0         1     0.929019         1.471248
 533         0         0         0         1     0.330204         0.903199
 267         0         0         1         0     0.330204        -0.232900
 389         0         0         0         1    -1.466241         0.903199
 317         1         0         0         0     0.030796        -1.368999
 374         0         0         0         1    -1.466241         0.903199
 36          0         0         0         1    -0.867426        -0.232900
 305         0         0         0         1     0.929019        -0.232900
 376         0         0         0         1    -1.466241        -0.232900
 102         0         0         0         1    -1.166834         0.335149
 403         1         0         0         0    -1.166834        -0.800950
 83          0         0         1         0     1.527833         0.903199
 427         1         0         0         0     0.330204         1.471248
 693         1         0         0         0    -0.568019        -1.368999
 77          0         0         0         1     0.929019        -0.232900
 ..        ...       ...       ...       ...          ...              ...
 657         0         0         1         0    -0.867426        -0.232900
 235         0         0         0         1    -0.268611         0.335149
 210         0         0         0         1     0.629611        -1.368999
 120         0         0         0         1     0.330204        -1.368999
 473         0         0         0         1     0.030796         0.903199
 623         0         0         0         1     0.030796        -0.800950
 109         0         0         0         1     1.527833        -0.232900
 25          0         0         0         1     0.330204        -1.368999
 665         0         0         0         1    -0.867426         0.903199
 586         0         0         0         1    -0.268611         1.471248
 677         1         0         0         0     0.629611        -0.232900
 369         0         0         0         1     0.030796         2.039298
 338         0         0         0         1     1.228426         0.335149
 175         1         0         0         0    -1.166834        -1.368999
 378         0         0         0         1    -1.466241         0.335149
 560         0         0         0         1     1.527833        -0.232900
 352         1         0         0         0     1.527833        -0.800950
 213         0         0         0         0     1.228426         1.471248
 333         0         0         0         1     1.228426        -0.800950
 79          0         0         0         1     0.929019         0.903199
 52          0         0         0         1     0.330204         2.039298
 100         0         0         0         1    -1.466241         0.335149
 600         1         0         0         0    -1.466241         0.335149
 28          0         0         1         0     0.330204        -0.232900
 174         0         0         0         1    -1.166834        -0.232900
 582         1         0         0         0    -1.765648        -0.232900
 477         0         0         0         1     0.030796        -0.800950
 474         0         0         0         1     0.030796         0.903199
 627         0         0         0         1     0.629611        -1.368999
 298         0         0         0         1     0.929019         0.903199

      Transportation Expense  Distance to Work       Age  \
 421                1.171843         -0.263140  1.032682
 414                1.624567         -0.939096 -1.320435
 548                1.036026          0.074838  0.562059
 649               -0.654143          1.426749  0.248310
 98                 0.387122         -0.330735  1.660180
 639                1.005844          0.412816 -0.536062
 612               -0.654143          1.426749  0.248310
 412               -0.654143          1.426749  0.248310
 164               -0.654143         -0.533522  0.562059
 663                2.092381          1.494345 -1.320435
 497               -1.574681         -1.344669  0.091435
 360               -1.016322         -1.209478 -0.379188
 153                0.040034         -0.263140 -1.320435
 217               -0.654143          1.426749  0.248310
 464                1.624567         -0.939096 -1.320435
 309               -1.574681         -1.141882  2.130803
 533               -1.574681         -1.344669  0.091435
 267                0.190942         -1.277074  0.091435
 389               -0.654143          1.426749  0.248310
 317               -1.574681         -1.344669  0.091435
 374               -0.654143          1.426749  0.248310
 36                 1.005844          0.412816 -0.536062
 305                0.190942         -0.668713  1.032682
 376               -0.654143          1.426749  0.248310
 102                0.040034         -0.263140 -1.320435
 403               -1.574681         -1.141882  2.130803
 83                -0.654143         -0.533522  0.562059
 427                2.213108         -0.871500 -0.849811
 693                0.190942         -0.939096 -0.692937
 77                 1.005844          0.412816 -0.536062
 ..                      ...               ...       ...
 657                0.387122         -0.330735  1.660180
 235                0.040034         -0.263140 -1.320435
 210               -1.016322         -1.209478 -0.379188
 120                0.040034         -0.263140 -1.320435
 473               -1.574681         -1.141882  2.130803
 623               -0.654143          1.426749  0.248310
 109                2.092381          1.494345 -1.320435
 25                 2.092381          1.494345 -1.320435
 665                0.190942         -1.277074  0.091435
 586                0.040034         -0.263140 -1.320435
 677               -1.574681         -1.344669  0.091435
 369               -1.574681         -1.344669  0.091435
 338               -0.654143          1.426749  0.248310
 175                0.040034         -0.263140 -1.320435
 378                0.356940         -0.330735  0.718933
 560                0.040034         -0.263140 -1.320435
 352                0.190942         -0.668713  1.032682
 213                0.854936         -1.682647  0.405184
 333               -0.654143          1.426749  0.248310
 79                 0.568211          1.359154 -0.065439
 52                 0.040034         -0.263140 -1.320435
 100               -1.574681         -1.141882  2.130803
 600               -0.654143         -0.263140 -1.006686
 28                 1.005844          0.412816 -0.536062
 174                0.040034         -0.263140 -1.320435
 582                1.005844          0.412816 -0.536062
 477                0.356940         -0.330735  0.718933
 474                2.092381          1.494345 -1.320435
 627               -0.654143         -0.263140 -1.006686
 298               -0.654143          1.426749  0.248310

      Daily Work Load Average  Body Mass Index  Education  Children       Pet
 421                -0.809957        -0.408580          0  0.880469  0.268487
 414                -0.809957        -0.408580          1 -0.919030 -0.589690
 548                -0.082083        -0.408580          0 -0.019280  0.268487
 649                -1.240355         1.002633          0 -0.919030 -0.589690
 98                 -0.262439         1.237836          0  0.880469  0.268487
 639                -1.240355         0.767431          0  0.880469  0.268487
 612                -0.188851         1.002633          0 -0.919030 -0.589690
 412                -0.809957         1.002633          0 -0.919030 -0.589690
 164                 1.786584        -1.114186          1  0.880469 -0.589690
 663                -0.637953         0.061825          0 -0.019280  2.843016
 497                -0.251187         0.297027          0 -0.919030 -0.589690
 360                 1.456728        -0.408580          0  0.880469 -0.589690
 153                 0.769711        -0.643782          0 -0.019280  1.126663
 217                 2.677510         1.002633          0 -0.919030 -0.589690
 464                -1.037971        -0.408580          1 -0.919030 -0.589690
 309                -0.169648         1.002633          0 -0.019280 -0.589690
 533                -0.082083         0.297027          0 -0.919030 -0.589690
 267                -0.154696         0.532229          1 -0.019280  0.268487
 389                -0.499679         1.002633          0 -0.919030 -0.589690
 317                 0.305783         0.297027          0 -0.919030 -0.589690
 374                -0.499679         1.002633          0 -0.919030 -0.589690
 36                 -1.647399         0.767431          0  0.880469  0.268487
 305                -0.169648         2.649049          0 -0.019280 -0.589690
 376                -0.499679         1.002633          0 -0.919030 -0.589690
 102                -0.262439        -0.643782          0 -0.019280  1.126663
 403                -0.685486         1.002633          0 -0.019280 -0.589690
 83                  0.863727        -1.114186          1  0.880469 -0.589690
 427                -0.643304        -0.408580          0  1.780219 -0.589690
 693                -0.853789        -0.408580          1 -0.919030 -0.589690
 77                 -0.458497         0.767431          0  0.880469  0.268487
 ..                       ...              ...        ...       ...       ...
 657                -0.637953         1.237836          0  0.880469  0.268487
 235                 2.644155        -0.643782          0 -0.019280  1.126663
 210                 2.677510        -0.408580          0  0.880469 -0.589690
 120                 0.919937        -0.643782          0 -0.019280  1.126663
 473                -1.037971         1.002633          0 -0.019280 -0.589690
 623                -1.240355         1.002633          0 -0.919030 -0.589690
 109                -0.262439         0.061825          0 -0.019280  2.843016
 25                 -1.647399         0.061825          0 -0.019280  2.843016
 665                -0.637953         0.532229          1 -0.019280  0.268487
 586                -0.188851        -0.643782          0 -0.019280  1.126663
 677                -0.853789         0.297027          0 -0.919030 -0.589690
 369                -0.499679         0.297027          0 -0.919030 -0.589690
 338                 0.305783         1.002633          0 -0.919030 -0.589690
 175                 1.786584        -0.643782          0 -0.019280  1.126663
 378                -0.499679        -0.878984          0 -0.919030 -0.589690
 560                 0.218718        -0.643782          0 -0.019280  1.126663
 352                -0.879469         2.649049          0 -0.019280 -0.589690
 213                 2.677510        -0.643782          0  0.880469 -0.589690
 333                 0.305783         1.002633          0 -0.919030 -0.589690
 79                 -0.458497        -0.878984          0  2.679969 -0.589690
 52                 -0.758273        -0.643782          0 -0.019280  1.126663
 100                -0.262439         1.002633          0 -0.019280 -0.589690
 600                -0.188851        -1.819793          1 -0.919030 -0.589690
 28                 -1.647399         0.767431          0  0.880469  0.268487
 174                 1.786584        -0.643782          0 -0.019280  1.126663
 582                 1.043433         0.767431          0  0.880469  0.268487
 477                -1.037971        -0.878984          0 -0.919030 -0.589690
 474                -1.037971         0.061825          0 -0.019280  2.843016
 627                -1.240355        -1.819793          1 -0.919030 -0.589690
 298                -0.169648         1.002633          0 -0.919030 -0.589690

 [525 rows x 14 columns],
      Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 571         1         0         0         0    -0.867426         2.039298
 105         0         0         0         1     0.629611         1.471248
 93          0         0         0         1     1.228426         0.903199
 505         0         0         0         1     0.629611        -0.800950
 242         0         0         0         1     0.030796         0.903199
 272         0         0         1         0     0.030796         1.471248
 198         0         0         1         0    -0.867426        -0.800950
 224         1         0         0         0    -0.268611         0.903199
 247         0         0         0         1     0.030796        -0.232900
 251         0         0         0         0     0.030796         0.335149
 396         0         0         0         1    -1.166834        -0.800950
 458         1         0         0         0    -0.268611        -0.800950
 448         0         0         0         1     1.527833        -0.232900
 90          0         0         0         1     1.228426        -0.232900
 277         0         0         0         0     0.629611        -0.800950
 622         1         0         0         0    -0.268611         2.039298
 299         1         0         0         0     0.929019         0.903199
 355         0         0         0         1     1.527833        -1.368999
 80          0         0         0         1    -0.568019        -1.368999
 420         1         0         0         0    -0.867426        -0.232900
 124         0         0         0         1    -1.765648        -0.232900
 194         1         0         0         0     0.330204         0.335149
 3           1         0         0         0     0.030796         0.335149
 295         1         0         0         0     1.527833         1.471248
 404         1         0         0         0    -1.166834        -0.232900
 219         0         0         0         1    -0.568019         0.903199
 188         0         0         0         1    -0.867426         0.335149
 55          0         0         0         0     0.629611        -0.800950
 388         0         0         0         1    -1.466241        -0.232900
 481         0         0         0         1     0.030796         1.471248
 ..        ...       ...       ...       ...          ...              ...
 6           0         0         0         1     0.030796         0.903199
 676         0         0         0         1     0.629611        -0.232900
 517         0         0         0         1     0.929019        -0.800950
 544         0         0         0         1     1.228426        -1.368999
 33          0         0         1         0     0.330204        -1.368999
 506         0         0         0         1     0.629611        -0.800950
 545         0         0         0         1     1.228426        -1.368999
 319         1         0         0         0     0.330204         0.335149
 689         0         0         0         1    -0.568019        -0.232900
 377         1         0         0         0    -1.466241         0.335149
 211         1         0         0         0     0.929019        -0.232900
 618         0         0         0         1    -0.568019         0.335149
 390         0         0         1         0     0.030796        -1.368999
 65          0         0         0         1     0.929019         0.335149
 449         0         0         0         1    -0.268611        -0.800950
 685         0         0         0         1    -0.568019        -1.368999
 405         0         0         0         0    -1.166834         0.335149
 518         0         0         0         1     0.929019        -0.800950
 674         0         0         0         1     0.030796         0.335149
 245         0         0         0         1     0.030796        -1.368999
 274         1         0         0         0     1.527833         0.903199
 509         0         0         0         1    -0.268611         1.471248
 222         1         0         0         0    -0.268611        -0.800950
 49          1         0         0         0     0.629611        -1.368999
 56          0         0         1         0     0.629611        -0.232900
 617         0         0         0         1    -1.466241         0.903199
 408         0         0         0         1    -1.166834         0.903199
 361         1         0         0         0    -1.166834        -0.232900
 379         0         0         0         1    -1.466241         0.903199
 555         1         0         0         0    -0.568019         0.903199

      Transportation Expense  Distance to Work       Age  \
 571               -0.654143         -0.263140 -1.006686
 105                2.092381          1.494345 -1.320435
 93                 0.568211          1.359154 -0.065439
 505                2.213108         -0.871500 -0.849811
 242               -1.016322         -1.209478 -0.379188
 272                1.005844          0.412816 -0.536062
 198                1.005844          0.412816 -0.536062
 224                0.356940         -0.330735  0.718933
 247                1.005844          0.412816 -0.536062
 251                0.568211          1.359154 -0.065439
 396               -0.654143         -0.533522  0.562059
 458                1.624567         -0.939096 -1.320435
 448               -0.654143          1.426749  0.248310
 90                 0.040034         -0.263140 -1.320435
 277                1.036026          1.359154 -0.692937
 622                0.085306         -1.074287  3.385799
 299               -0.654143         -0.263140 -1.006686
 355               -0.986140         -0.195544 -1.163560
 80                -0.654143          1.426749  0.248310
 420               -1.574681         -1.141882  2.130803
 124               -1.574681         -1.344669  0.091435
 194                0.356940         -0.330735  0.718933
 3                  0.854936         -1.682647  0.405184
 295               -0.654143         -0.263140 -1.006686
 404               -1.574681         -1.141882  2.130803
 219                2.092381          1.494345 -1.320435
 188               -1.016322         -1.209478 -0.379188
 55                -1.574681         -1.141882  2.130803
 388               -0.654143          1.426749  0.248310
 481               -0.654143         -0.533522  0.562059
 ..                      ...               ...       ...
 6                  2.092381          1.494345 -1.320435
 676                0.190942         -0.939096 -0.692937
 517                2.213108         -0.871500 -0.849811
 544               -0.654143          1.426749  0.248310
 33                 0.190942         -0.060353  1.817054
 506                2.092381          1.494345 -1.320435
 545               -1.574681         -1.344669  0.091435
 319               -0.654143          1.426749  0.248310

The output we obtain here consist of 4 arrays,
Array 1 is a training datasets with inputs,
Array 2 is a traiding dataset with targets
Array 3 is a test
Array 4 is a test datasets  with targets

In [84]:
# declare 4 variables for the split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [85]:
# check the shape of the train inputs and targets
print (x_train.shape, y_train.shape)

(560, 14) (560,)

As you can see the training inputs are 560 by 14 and our training targets are 560. This tell us that, the inputs contain 560 observations along 14 variables, while the targets are vector of lenth 560

Our test include 140 observations and 14 input variables and 1 target variable. 

Therefore, this method has basically split the scaled inputs and target inputs into matching forms that we can now use in our machine learning.

In [86]:
# check the shape of the test inputs and targets
print (x_test.shape, y_test.shape)

(140, 14) (140,)

This mean that, 80% of the observations will help us for training and 20% will be for testing

## Logistic regression with sklearn

In [87]:
# import the LogReg model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

### Training the model

In [88]:
# create a logistic regression object
reg = LogisticRegression()

In [89]:
# fit our train inputs
# that is basically the whole training part of the machine learning
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [90]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

0.7660714285714286

Our results is 0.76. So we can conclude that our model has an accuracy of 0.78 or 80% this means that our model learned to classified 80% of the observations correctly

### Manually check the accuracy

In [91]:
# find the model outputs according to our model. We shall store these information in a new variable called model_outputs
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

We can see an array we 0 and 1

In [92]:
# compare them with the targets
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [93]:
# ACTUALLY compare the two variables
model_outputs == y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True, False,
       False, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

This array will company the elements of the 2 variables, and if there's a match, the results is true otherwise, it is false and now we can clearly see which elements have been guess correctly, and which ones haven't. So this means that true is the same as 1 and false is the same as zero

So lets sum this up and see what reseults we will have.

In [94]:
# find out in how many instances we predicted correctly
np.sum((model_outputs==y_train))

429

The results will be the total number true entries of correct predictions

In [95]:
# get the total number of instances
model_outputs.shape[0]

560

In [96]:
# calculate the accuracy of the model
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7660714285714286

### Finding the intercept and coefficients

In [97]:
# get the intercept (bias) of our model
reg.intercept_

array([-1.43101781])

In [98]:
# get the coefficients (weights) of our model
reg.coef_

array([[ 2.61893423,  0.83461948,  2.95258195,  0.64428488,  0.01123706,
        -0.0748093 ,  0.62180009, -0.02934223, -0.17585164, -0.02583315,
         0.27705024, -0.29385863,  0.3549178 , -0.27486307]])

In [99]:
# check what were the names of our columns
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [100]:
# save the names of the columns in an ad-hoc variable
feature_name = unscaled_inputs.columns.values

In [101]:
# use the coefficients from this table (they will be exported later and will be used in Tableau)
# transpose the model coefficients (model.coef_) and throws them into a df (a vertical organization, so that they can be
# multiplied by certain matrices later) 
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

               Feature name  Coefficient
0                  Reason_1     2.618934
1                  Reason_2     0.834619
2                  Reason_3     2.952582
3                  Reason_4     0.644285
4               Month Value     0.011237
5           Day of the Week    -0.074809
6    Transportation Expense     0.621800
7          Distance to Work    -0.029342
8                       Age    -0.175852
9   Daily Work Load Average    -0.025833
10          Body Mass Index     0.277050
11                Education    -0.293859
12                 Children     0.354918
13                      Pet    -0.274863

In [102]:
# do a little Python trick to move the intercept to the top of the summary table
# move all indices by 1
summary_table.index = summary_table.index + 1

# We will add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

               Feature name  Coefficient
0                 Intercept    -1.431018
1                  Reason_1     2.618934
2                  Reason_2     0.834619
3                  Reason_3     2.952582
4                  Reason_4     0.644285
5               Month Value     0.011237
6           Day of the Week    -0.074809
7    Transportation Expense     0.621800
8          Distance to Work    -0.029342
9                       Age    -0.175852
10  Daily Work Load Average    -0.025833
11          Body Mass Index     0.277050
12                Education    -0.293859
13                 Children     0.354918
14                      Pet    -0.274863

## Interpreting the coefficients

Coefficients can also be called weight and Interceptions can be called bias. The weight shows how we weigh a certain input and the closer they are to 0, the smaller the weight. Alternatively, the further away from 0, the bigger the weight will be.

These standardized coeficients are basically the coefficients of a regression when all variables have been standardized.

Other packages in software include the standard coefficient because they allow for a simply and easy to understand companrison between the 2 variables. So we can say that, whichever weights is bigger, its corresponding feature is more important.
For a machine learning purposes, and predictions in general, the variables are usually standardized like we will be doing below.

Another thing will have to note here is that when ever we are dealing with a logistic regretion, the coefficients we are predicting are known as logg(odds) logistics regressions are nothing but a linear regression, and predicting log(odds) means that they will later be transfered int o and 1

In [103]:
# create a new Series called: 'Odds ratio' which will show the.. odds ratio of each feature
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [104]:
# display the df
summary_table

               Feature name  Coefficient  Odds_ratio
0                 Intercept    -1.431018    0.239065
1                  Reason_1     2.618934   13.721092
2                  Reason_2     0.834619    2.303937
3                  Reason_3     2.952582   19.155348
4                  Reason_4     0.644285    1.904625
5               Month Value     0.011237    1.011300
6           Day of the Week    -0.074809    0.927920
7    Transportation Expense     0.621800    1.862277
8          Distance to Work    -0.029342    0.971084
9                       Age    -0.175852    0.838742
10  Daily Work Load Average    -0.025833    0.974498
11          Body Mass Index     0.277050    1.319233
12                Education    -0.293859    0.745382
13                 Children     0.354918    1.426063
14                      Pet    -0.274863    0.759676

This has added a new column to our table known as Odds_ratio
The next thing i will do is to sort the data table

In [105]:
# sort the table according to odds ratio
# note that by default, the sort_values method sorts values by 'ascending'
summary_table.sort_values('Odds_ratio', ascending=False)

               Feature name  Coefficient  Odds_ratio
3                  Reason_3     2.952582   19.155348
1                  Reason_1     2.618934   13.721092
2                  Reason_2     0.834619    2.303937
4                  Reason_4     0.644285    1.904625
7    Transportation Expense     0.621800    1.862277
13                 Children     0.354918    1.426063
11          Body Mass Index     0.277050    1.319233
5               Month Value     0.011237    1.011300
10  Daily Work Load Average    -0.025833    0.974498
8          Distance to Work    -0.029342    0.971084
6           Day of the Week    -0.074809    0.927920
9                       Age    -0.175852    0.838742
14                      Pet    -0.274863    0.759676
12                Education    -0.293859    0.745382
0                 Intercept    -1.431018    0.239065

Our table has been sorted with the most important at the top and least important at the bottom.

How to interpret them.
-
If its coefficient is around 0, or if its odds ratio is around 1, this means that the corresponding feature is not particularly important.

This reasoning in terms of weight is that, A weight coefficient of o implies that no matter the feature value, we will multiply it by 0 in the model and the whole results will be 0.

However, for a unit change in the standardized feature, the odds increase by a multiple equal to the odds ratio (1= no change)

Finally, by looking at the coefficient table, we can notice that the most strongly pronouce feafures, seems to be the 4 reasons for absence, followed by the transportation expense, and whether a person has children pets or education, but these are at the bottom of the table but they are still far away from zero so they are still very important. whereas the days of the week, distance to work, Daily work load average and month values seems to have the smallest impacts the weights of these are almost zero so regardless of their value, they will barely affect our model.

So our last question will be about the reasons and what could be the various impacts of the various reasons?

A quick recap of what our various reasons stance for. 
Reason 0 or no reason baseline model (when no reason is given)
Reason is comprise pf tje various diseases,
Reason is related to prenancy and giving birth
Reason 3 is regarding poisoning and perculiar reasons and not categorized elsewhere and ,
Reason 4 is related to light diseases.

In the light of this, we can easily understand out coefficiency very well which implies that the most crucial reason for absening is poisoning, so basically, if you are poison you can't go to work.

The weight means the ratio of someone being excessively absent after being poisoned are 20 times higher when no reason was reported.

Another very important reason seems to be number 1 or various diseases. This can also be called the normal absenteeism case. You got sick and you skipped work. A person who report this is 14 times likely to be absent from work than a person who didn't specify a reason.

The last but the not the list, we have pregnancy and giving birth.
I particularly like this one because it is a prominent cause of absenteeism, but at the same time is a way less pronouced than reasons 1 and 3. Our logic for this is that a woman who is pregnant can get permissions go to the hospital do her regular checkups and can go back to work, so there's nothing excessive about it. But from the Odds ratio, we can verify that a person with this reason only has about 3 times likely to be absent just because of some emergencies.

Finally we got the transportation and this is the most important non dummy variable in the model from it's odd ratio it means that for 1 standardized unit or 1 standard deviation increased in the transportation expense, it is close to twice a person is likely to be absent from work.

We chose standardization model for our final predictions because we prefer models with higher accuracy.

## Testing the model

In [106]:
# assess the test accuracy of the model
reg.score(x_test,y_test)

0.75

So based oon the data that the model has never seen before, in 0.75 or 75% of the cases the model will predict correctly if a person is going to be excessively absent. Therefore, the test accuracy is always less than the train accuracy

In [107]:
# find the predicted probabilities of each class
# the first column shows the probability of a particular observation to be 0, while the second one - to be 1
predicted_proba = reg.predict_proba(x_test)

# let's check that out
predicted_proba

array([[0.75682339, 0.24317661],
       [0.62536317, 0.37463683],
       [0.45822353, 0.54177647],
       [0.77099925, 0.22900075],
       [0.07542628, 0.92457372],
       [0.28278905, 0.71721095],
       [0.29801542, 0.70198458],
       [0.11048155, 0.88951845],
       [0.75171606, 0.24828394],
       [0.75523413, 0.24476587],
       [0.49875222, 0.50124778],
       [0.1833379 , 0.8166621 ],
       [0.06890587, 0.93109413],
       [0.68279499, 0.31720501],
       [0.27519922, 0.72480078],
       [0.50169625, 0.49830375],
       [0.51665478, 0.48334522],
       [0.55270605, 0.44729395],
       [0.38141173, 0.61858827],
       [0.05610613, 0.94389387],
       [0.73260604, 0.26739396],
       [0.76341003, 0.23658997],
       [0.43900234, 0.56099766],
       [0.45668906, 0.54331094],
       [0.21871703, 0.78128297],
       [0.7527246 , 0.2472754 ],
       [0.49467696, 0.50532304],
       [0.87470731, 0.12529269],
       [0.23052358, 0.76947642],
       [0.75564902, 0.24435098],
       [0.59972216, 0.40027784],
       [0.27717787, 0.72282213],
       [0.31690792, 0.68309208],
       [0.49816211, 0.50183789],
       [0.76341003, 0.23658997],
       [0.42509638, 0.57490362],
       [0.73755175, 0.26244825],
       [0.23677191, 0.76322809],
       [0.54929812, 0.45070188],
       [0.41058536, 0.58941464],
       [0.7454534 , 0.2545466 ],
       [0.54623527, 0.45376473],
       [0.7557309 , 0.2442691 ],
       [0.56545738, 0.43454262],
       [0.19771078, 0.80228922],
       [0.35332232, 0.64667768],
       [0.25809916, 0.74190084],
       [0.74868416, 0.25131584],
       [0.73126718, 0.26873282],
       [0.78239674, 0.21760326],
       [0.4812022 , 0.5187978 ],
       [0.66070446, 0.33929554],
       [0.30789518, 0.69210482],
       [0.73674192, 0.26325808],
       [0.15891505, 0.84108495],
       [0.58153683, 0.41846317],
       [0.08382852, 0.91617148],
       [0.70356138, 0.29643862],
       [0.64966867, 0.35033133],
       [0.65426789, 0.34573211],
       [0.26835428, 0.73164572],
       [0.33156361, 0.66843639],
       [0.70994288, 0.29005712],
       [0.20823712, 0.79176288],
       [0.75075519, 0.24924481],
       [0.75421833, 0.24578167],
       [0.91026544, 0.08973456],
       [0.74973059, 0.25026941],
       [0.22872649, 0.77127351],
       [0.67919324, 0.32080676],
       [0.74615922, 0.25384078],
       [0.65075798, 0.34924202],
       [0.10587054, 0.89412946],
       [0.55453195, 0.44546805],
       [0.38935777, 0.61064223],
       [0.75564902, 0.24435098],
       [0.21557298, 0.78442702],
       [0.26031535, 0.73968465],
       [0.2701542 , 0.7298458 ],
       [0.34829838, 0.65170162],
       [0.7289181 , 0.2710819 ],
       [0.9035441 , 0.0964559 ],
       [0.71986424, 0.28013576],
       [0.29281039, 0.70718961],
       [0.5406227 , 0.4593773 ],
       [0.87470334, 0.12529666],
       [0.2998686 , 0.7001314 ],
       [0.46475768, 0.53524232],
       [0.74874668, 0.25125332],
       [0.28577191, 0.71422809],
       [0.81514504, 0.18485496],
       [0.87546767, 0.12453233],
       [0.73591021, 0.26408979],
       [0.76316388, 0.23683612],
       [0.77060252, 0.22939748],
       [0.11537221, 0.88462779],
       [0.76727804, 0.23272196],
       [0.24456058, 0.75543942],
       [0.75917958, 0.24082042],
       [0.79030859, 0.20969141],
       [0.39846218, 0.60153782],
       [0.26874502, 0.73125498],
       [0.29439874, 0.70560126],
       [0.32424045, 0.67575955],
       [0.56478932, 0.43521068],
       [0.56659875, 0.43340125],
       [0.77172384, 0.22827616],
       [0.12903509, 0.87096491],
       [0.25326796, 0.74673204],
       [0.85150515, 0.14849485],
       [0.90402263, 0.09597737],
       [0.08884483, 0.91115517],
       [0.32658519, 0.67341481],
       [0.59412713, 0.40587287],
       [0.43191425, 0.56808575],
       [0.38910244, 0.61089756],
       [0.22821478, 0.77178522],
       [0.16781462, 0.83218538],
       [0.42989947, 0.57010053],
       [0.71036682, 0.28963318],
       [0.76613683, 0.23386317],
       [0.86658008, 0.13341992],
       [0.17966914, 0.82033086],
       [0.48515236, 0.51484764],
       [0.74517046, 0.25482954],
       [0.70731775, 0.29268225],
       [0.76887947, 0.23112053],
       [0.85499662, 0.14500338],
       [0.31430624, 0.68569376],
       [0.71929279, 0.28070721],
       [0.37091913, 0.62908087],
       [0.75977928, 0.24022072],
       [0.76387821, 0.23612179],
       [0.70241849, 0.29758151],
       [0.7158651 , 0.2841349 ],
       [0.42470405, 0.57529595],
       [0.54751302, 0.45248698],
       [0.70108314, 0.29891686],
       [0.73510906, 0.26489094],
       [0.52767547, 0.47232453]])

In [108]:
predicted_proba.shape

(140, 2)

Our results shows that there are 140 test observation and 2 columns

In [109]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.24317661, 0.37463683, 0.54177647, 0.22900075, 0.92457372,
       0.71721095, 0.70198458, 0.88951845, 0.24828394, 0.24476587,
       0.50124778, 0.8166621 , 0.93109413, 0.31720501, 0.72480078,
       0.49830375, 0.48334522, 0.44729395, 0.61858827, 0.94389387,
       0.26739396, 0.23658997, 0.56099766, 0.54331094, 0.78128297,
       0.2472754 , 0.50532304, 0.12529269, 0.76947642, 0.24435098,
       0.40027784, 0.72282213, 0.68309208, 0.50183789, 0.23658997,
       0.57490362, 0.26244825, 0.76322809, 0.45070188, 0.58941464,
       0.2545466 , 0.45376473, 0.2442691 , 0.43454262, 0.80228922,
       0.64667768, 0.74190084, 0.25131584, 0.26873282, 0.21760326,
       0.5187978 , 0.33929554, 0.69210482, 0.26325808, 0.84108495,
       0.41846317, 0.91617148, 0.29643862, 0.35033133, 0.34573211,
       0.73164572, 0.66843639, 0.29005712, 0.79176288, 0.24924481,
       0.24578167, 0.08973456, 0.25026941, 0.77127351, 0.32080676,
       0.25384078, 0.34924202, 0.89412946, 0.44546805, 0.61064223,
       0.24435098, 0.78442702, 0.73968465, 0.7298458 , 0.65170162,
       0.2710819 , 0.0964559 , 0.28013576, 0.70718961, 0.4593773 ,
       0.12529666, 0.7001314 , 0.53524232, 0.25125332, 0.71422809,
       0.18485496, 0.12453233, 0.26408979, 0.23683612, 0.22939748,
       0.88462779, 0.23272196, 0.75543942, 0.24082042, 0.20969141,
       0.60153782, 0.73125498, 0.70560126, 0.67575955, 0.43521068,
       0.43340125, 0.22827616, 0.87096491, 0.74673204, 0.14849485,
       0.09597737, 0.91115517, 0.67341481, 0.40587287, 0.56808575,
       0.61089756, 0.77178522, 0.83218538, 0.57010053, 0.28963318,
       0.23386317, 0.13341992, 0.82033086, 0.51484764, 0.25482954,
       0.29268225, 0.23112053, 0.14500338, 0.68569376, 0.28070721,
       0.62908087, 0.24022072, 0.23612179, 0.29758151, 0.2841349 ,
       0.57529595, 0.45248698, 0.29891686, 0.26489094, 0.47232453])

In reality, logistics regression models calculate these probabilities in the background. If the probability is below 0.5, it places a 0 and if it is above 0.5, it places a 1

## Save the model

In [110]:
# import the relevant module
import pickle

In [111]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [112]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)